### PR TITLE
Make XinTongYuan as co-organizer

### PR DESCRIPTION
**Pull request by lgn21st**
Make XinTongYuan as co-organizer instead of organizer.

### CODE REVIEW

**Review by Hoverbear — APPROVED** [review]
LGTM, but what about the footer?

**Comment by Aimeedeer** [comment]
Page Image
Footer Image
Is that possible?

**Comment by Hoverbear** [comment]
@Aimeedeer What if we change "Sponsors" to "Supporters" and put their level in brackets for the footer.

Eg:

* Baidu X-Lab (Gold)
...

* CAICT (Co-host)

**Comment by Aimeedeer** [comment]
I guess no problem, sequence is gold, silver, bronze, (other supports) and co-organizer at the last.

**Pull request merged**
