### PR TITLE
Speakers

### PR DESCRIPTION
**Pull request by Hoverbear**
Post our speakers! :)

### CODE REVIEW

**Comment by ymjing** [comment]
Fyi, the photo of Mingshen Sun (speaker of "Linux From Scratch in Rust") is available at https://mssun.me/photo.jpg.

The photo of Yu Ding (speaker of "Build a Secure and Trusted Framework in Rust") is available at https://paris.rustfest.eu/assets/paris/speakers/yu.jpg

**Comment by Hoverbear** [comment]
Having two photos of them for the workshop takes up a lot of space, I wonder if we could get a photo of them together...

**Comment by ymjing** [comment]
The workshop titled "Build a Secure and Trusted Framework in Rust" may use Yu Ding's headshot (https://paris.rustfest.eu/assets/paris/speakers/yu.jpg) instead of Mingshen Sun's. :)

**Comment by Hoverbear** [comment]
@kevinis Both are presenting. I need to mush them together.... moment...

**Comment by Hoverbear** [comment]
There, that looks better :) PTAL @kevinis

**Comment by ymjing** [comment]
@Hoverbear It looks great to me!

**Comment by Aimeedeer** [comment]
Alex's photo
speaker Alex

**Pull request merged**
