### PR TITLE
[wip] add a list of program committee members to index.html

### PR DESCRIPTION
**Pull request by ymjing**
This PR adds a list of program committee members to index.html. The members are sorted alphabetically by the first names. 

**This is a work in progress.**

1. It would be better to place the list in `content/about.md`. But I don't know how to get the `range` shortcode working in Markdown;
2. The last `figure` is positioned slightly lower that the other members. Looks like a css problem; help is needed.
3. Some of the pictures were fetched from Twitter or Github profile pages. Committee members may contribute to this PR and replace the image file in `static/img/headfigures`. Note that images are 400px by 400 px.

### CODE REVIEW

**Comment by Hoverbear** [comment]
Oh! At the moment @skade isn't participating in the CFP review committee (He just maintains it)... Though he's welcome to participate if he wants!

**Comment by ymjing** [comment]
No problem. We can update this PR after the review committee meeting next week.

**Comment by Hoverbear** [comment]
Great! Rest LGTM! :)

**Comment by Hoverbear** [comment]
@kevinis Still waiting for the removal of @skade from this PR then we're good to merge! :)

**Comment by ymjing** [comment]
@Hoverbear. I'm waiting for the final program page to see if it's a better place to show the committee list. But we can move it later if necessary.

**Comment by ymjing** [comment]
@Hoverbear This is ready!

**Comment by Hoverbear** [comment]
@kevinis I think on the Schedule page is better maybe? #7 ?

**Comment by ymjing** [comment]
@Hoverbear Sure. I can do it after the schedule is out.

**Comment by Hoverbear** [comment]
@kevinis I'll merge this branch into that PR. :) Thanks for this.

**Pull request closed without merging**
